[package]
name = "tvix-eval-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tvix-eval = { path = "./tvix/eval", default-features = false }
wasm-bindgen = "0.2"
