[package]
name = "tvix-eval-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tvix-eval = { path = "./tvix/eval", default-features = false }
wasm-bindgen = "0.2"
include_dir = "0.7"
rustc-hash = "1.1.0"
bytes = "1.0"
